config:
  potato-war:
    template: "  {#yellow}%s. {#blue}%s {#white}- {#red}%s"
    ui:
      - "{#yellow}------------[{#green}{msg#title}{#yellow}]------------"
      - "%s"
    announce-ui:
      - "{color(yellow)} ─────────────────────────────────"
      - " {msg#hint}"
      - "{color(yellow)} ─────────────────────────────────"