config:
  explosion_defender:
    override_explosion: true
    record: true
    broadcast: false
  protection_area:
    record: true
    broadcast: false
    op_ignore: true
  item_defender:
    record: true
    broadcast: false
    op_ignore: true
    illegal_list:
      - "__placeholder__"
    warning_list:
      - "tnt"
      - "flint_and_steel"
      - "lava_bucket"
  ip_defender:
    record: true
    auto_ban: false
    auto_ban_day_time: 0
    auto_ban_hour_time: 0
    auto_ban_minute_time: 10
    auto_ban_second_time: 0
  we_size_defender:
    selection_size: 128
    operation_size: 16
    total_size: 1024
  permission_manager:
    default_group: player
    groups:
      operator:
        allow:
          - minecraft.command.*
          - worldedit.*
        disallow:
      player:
        allow:
          - modifyworld.*
          - worldedit.selection.pos
          - worldedit.selection.cuboid
          - worldedit.clipboard.cut
          - worldedit.clipboard.copy
          - worldedit.help
          - worldedit.biome.*
          - worldedit.schematic.list
          - worldedit.schematic.save
          - worldedit.clipboard.save
          - worldedit.history.*
          - worldedit.navigation.*
          - worldedit.region.*
          - minecraft.command.tp
          - minecraft.command.gamemode
        disallow:
      guest:
        allow:
          - minecraft.command.tp
        disallow:
          - minecraft.command.tp
          - worldedit.*
