config:
  explosion-defender:
    override-explosion: true
    record: true
    broadcast: true
  protection-area:
    record: true
    broadcast: false
    op-ignore: true
  item-defender:
    record: true
    broadcast: false
    op-ignore: true
    illegal-list:
      - "--placeholder--"
    warning-list:
      - "tnt"
      - "flint_and_steel"
      - "lava_bucket"
      - "water_bucket"
      - "respawn_anchor"
      - "end_crystal"
  we-session-size-limit:
    max-selection-size: 128
    max-edit-size: 384
  ip-defender:
    record: true #是否记录IP属地变化
    auto-ban: false #是否自动封禁
    auto-ban-day-time: 0 #封禁的时间，往下为天，时，分，秒
    auto-ban-hour-time: 0
    auto-ban-minute-time: 10
    auto-ban-second-time: 0
  permission-manager:
    default-group: player