#file: noinspection HttpUrlsUsage
config:
  explosion-defender:
    override-explosion: true
    record: true
    broadcast: true
  protection-area:
    record: true
    broadcast: false
    op-ignore: true
  item-defender:
    record: true
    broadcast: false
    op-ignore: true
    illegal-list:
      - "--placeholder--"
    warning-list:
      - "tnt"
      - "flint_and_steel"
      - "lava_bucket"
      - "water_bucket"
      - "respawn_anchor"
      - "end_crystal"
  we-size-defender:
    selection-size: 128
    operation-size: 16
    total-size: 1024
  ip-defender:
    record: true
    auto-ban: false
    auto-ban-day-time: 0
    auto-ban-hour-time: 0
    auto-ban-minute-time: 10
    auto-ban-second-time: 0
  permission-manager:
    default-group: player