config:
  custom-kick-message:
    ui:
      - '{#yellow}>> {msg#header} {#yellow}<<'
      - '{#return}'
      - '{#reset}{reason}{#return}{#return}'
      - '{msg#website-hint}'
    ban-ui:
      - '{#yellow}>> {msg#ban-header} {#yellow}<<'
      - '{#return}'
      - '{#reset}{msg#@type}'
      - '{msg#ban-hint}{#return}'
      - '{msg#ban-reason}{#return}{#return}'
      - '{msg#ban-info}'
      - '{msg#website-hint}'
  bossbar-announcement:
    period: 1200
    bar-color: white
    ui: '{#purple}{#server-name-plain} {#yellow}>> {rand#text}'
  player-name-header:
    template: "[{#white}{header}{#white}] {player}"
    op-header: '{#dark-purple}管理'
    player-header: '{#dark-aqua}玩家'
    below-name: " {msg#custom-scoreboard:play-time}  {msg#custom-scoreboard:ping}"
    below-name-enable: false
  chat-announce:
    period: 12000
    ui:
      - "{#yellow}一一一一一一一一一一一一一一一一一一一一一一一一一一一"
      - "%s"
      - "%s"
      - "{#yellow}一一一一一一一一一一一一一一一一一一一一一一一一一一一"
  join-quit-message:
    proxy: /{$proxy}
    sound: true
    volume: 0.25