config:
  protection-area:
    record: true
    broadcast: false
    op-ignore: true
  item-defender:
    record: true
    broadcast: false
    op-ignore: true
    illegal-list:
      - "--placeholder--"
    warning-list:
      - "tnt"
      - "flint_and_steel"
      - "lava_bucket"
      - "water_bucket"
      - "respawn_anchor"
      - "end_crystal"
  we-session-size-limit:
    max-selection-size: 128
    max-edit-size: 384
