config:
  tab-menu:
    header-ui:
      - '{#dark-gray}一一一一一一一一一一一一一一一一一一一一一一一一一一一一'
      - '{#yellow}>> {#white} {msg#welcome-header} {#yellow} <<{#white}'
      - '{msg#player}    {msg#max-player}'
    footer-ui:
      - ' '
      - '{msg#tps}   {msg#mspt}   {msg#ping}'
      - '{msg#date}'
      - '{#dark-gray}一一一一一一一一一一一一一一一一一一一一一一一一一一一一'
  custom-ban-message:
    ui:
      - '{#yellow}>> {msg#header} {#yellow}<<'
      - '{#return}'
      - '{#reset}{msg#@type}'
      - '{msg#hint}{#return}'
      - '{msg#reason}{#return}{#return}'
      - '{msg#info}'
      - '{msg#website-hint}'
  custom-kick-message:
    ui:
      - '{#yellow}>> {msg#header} {#yellow}<<'
      - '{#return}'
      - '{#reset}{reason}{#return}{#return}'
      - '{msg#website-hint}'
  bossbar-announcement:
    period: 1200
    bar-color: white
    ui: '{#purple}{#server-name-plain} {#yellow}>> {rand#text}'
  chat-format:
    world: "common:world:%s"
    time: "<post>   {#gray}%s"
    template: '[{#white}{world}{#white}]{0} {color(gold)}> {color(gray)}{1} {time}'
  player-name-header:
    template: "[{#white}{header}{#white}] {player}"
    op-header: '{#dark-purple}管理'
    player-header: '{#dark-aqua}玩家'
    below-name: " {msg#custom-scoreboard:play-time}  {msg#custom-scoreboard:ping}"
  welcome-message:
    ui:
      - "{#yellow}一一一一一一一一一一一一一一一一一一一一一一一一一一一"
      - "{msg#title}"
      - '  {msg#content}'
      - ' '
      - '  {msg#callback}'
      - "{#yellow}一一一一一一一一一一一一一一一一一一一一一一一一一一一"
  custom-scoreboard:
    ui:
      - ' '
      - ' {msg#date}'
      - ' {msg#time}'
      - ' '
      - ' {msg#player}'
      - ' {msg#rank}'
      - ' {msg#play-time}'
      - ' {msg#world-time}'
      - ' '
      - ' {msg#player-count}'
      - ' {msg#ping}'
      - ' '
      - ' {msg#qq-group}'
      - ' {msg#website}'
      - ' '
  chat-announce:
    period: 12000
    ui:
      - "{#yellow}一一一一一一一一一一一一一一一一一一一一一一一一一一一"
      - "%s"
      - "%s"
      - "{#yellow}一一一一一一一一一一一一一一一一一一一一一一一一一一一"
  join-quit-message:
    proxy: /{$proxy}
    sound: true
    volume: 0.25
  custom-death-message:
    prefix: "{#gray}[{#red}X{#gray}]{#reset}"
    suffix: ""
  afk:
    timeout: 1200