config:
  --features:
    stp-command: true
    hub-command: true
    stpa-command: true
    motd-sync: true
    tab-sync: true
    chat-sync: true
    legacy-forwarding-protect: true
    server-statement-observer: true
    server-transfer-message: true
    proxy-ping: true
    apm-service: true
  apm-service:
    exchange: true #is connector exchange?
    host: '127.0.0.1' #host to bind connector
    port: 25843 #port to bind connector
    identifier: 'proxy' #identifier for apm to use
    key: 'test' # always change key after installed!
  motd-sync:
    provider: "lobby"
    max-players: 2024
    hide-players: false
    update-interval: 15
  tab-sync:
    format: "{color(gold)}[%s{color(gold)}] {color(gray)}%s"
  chat-sync:
    template: "{color(gold)}[%s{color(gold)}] {color(gray)}%s: "
