config:
  minecart-controller:
    ui: '{run-mode}{#white}({msg#level}{level}) {#yellow}|{#white} {msg#speed}{speed} {#yellow}|{#white} {msg#acceleration}{acceleration}m/s^2'
    max-speed: 1.5
    thrust-1-acceleration: 0.08
    thrust-2-acceleration: 0.16
    thrust-3-acceleration: 0.27
    thrust-4-acceleration: 0.32
    thrust--1-acceleration: -0.08
    thrust--2-acceleration: -0.29
    thrust--3-acceleration: -0.32
    thrust--4-acceleration: -0.5
  waypoint:
    allow-coordinate-add: true
    home: true
    back-to-death: true
  music-player:
    ui: "{#white}{msg#playing} {#yellow}: {#aqua}{name} {#yellow}|{#white} {time}{#gray} / {#white}{total}"
    remote: false
    cdn-server: lobby
    pitch-offsets:
      "Kiss_The_Rain.mid": -12
  realistic-sleep:
    scale-per-player: 3.5
    health-interval: 20
    health-amount: 1
  item-counter:
    postfix: "{#red} | {#white}StatTrak™"