config:
  vanilla-tweaks:
    double-door-sync: true
    dispenser-block-placing: true
  time-scale:
    scale-factor: 10
    sync-with-real-time: false
  realistic-sleep:
    scale-per-player: 3.5
    health-interval: 20
    health-amount: 1
