config:
  config_version: 3
  message:
    module_command_exception: "[{red}模块{white}]{gray}服务器无法理解命令,或你没有权限。"
    module_enable_success: "[{green}模块{white}]{gray}成功启用模块 %s。"
    module_disable_success: "[{green}模块{white}]{gray}成功停用模块 %s。"
    module_reload_success: "[{green}模块{white}]{gray}成功重载模块 %s。"
    module_reload_config_success: "[{green}模块{white}]{gray}成功刷新模块 %s 的配置文件。"
    module_enable_all_success: "[{green}模块{white}]{gray}全部模块已完成启动，具体情况请参考聊天输出。"
    module_disable_all_success: "[{green}模块{white}]{gray}全部模块已完成停止，具体情况请参考聊天输出。"
    module_reload_all_success: "[{green}模块{white}]{gray}全部模块已完成重载，具体情况请参考聊天输出。"
    module_reload_all_config_success: "[{green}模块{white}]{gray}全部模块已完成配置文件刷新。"
    module_enable_failed: "[{orange}模块{white}]{gray}无法启动模块 %s ,请查看服务端日志。"
    module_disable_failed: "[{orange}模块{white}]{gray}无法关闭模块 %s ,请查看服务端日志。"
    module_reload_failed: "[{orange}模块{white}]{gray}无法重载模块 %s ,请查看服务端日志。"
    module_list_all: "[{aqua}模块{white}]{gray}以下是所有模块：\n %s"
    module_info: "[{aqua}模块{white}]{gray}以下是模块 %s 的信息(模块输出): "
    module_status_locked: "[{red}模块{white}]{gray}对模块状态的修改已被配置文件锁定。"
    player_data_command_exception: "[{red}数据{white}]{gray}服务器无法理解命令,或你没有权限。"
    player_data_delete_success: "[{green}数据{white}]{gray}成功删除了%s的玩家数据。"
    player_token_info: "[{aqua}凭据{white}]{gray}你的默认凭据为 %s ,你可以随时用/set_player_token [凭据] 来更改它!"
    player_token_set: "[{green}凭据{white}]{gray}你的凭据已被设为 %s !"
    package_import: "[{light_purple}模块{white}]{gray}检测到新的quark内容包组 %s, 导入..."
    package_import_success: "[{light_purple}模块{white}]{gray}导入完成。"
  config:
    default_module_status: true
    module_status_locked: false
    http_server_host: 127.0.0.1
    http_server_port: 11451
    http_cors_address: http://localhost:63342
  modules:
    quark_core:core: true
  global_text:
    server_name: quark Example-Server
    website: https://flybird.ink




