config:
  plugin:
    fast-boot: false
    debug: false
    metrics: true
  default-status:
    module: true
    package: true
  environment:
    proxy: false
    proxy-id: example-server
    proxy-exchange-mode: false
    proxy-exchange-host: example.com
    proxy-exchange-port: 25843
    proxy-exchange-key: "(enter your custom key)"
    smtp-server: smtp.example.com:25
    smtp-user: example@example.com
    smtp-password: "(enter your custom key)"
