config:
  task:
    async: true
    threads: 16
  disabled-service:
    - http-service
    - remote-message-service
  smtp-service:
    server: smtp.example.com:25
    username: example@example.com
    password: example-password
  http-service:
    host: 127.0.0.1
    port: 8125
    backlog: 10
    threads: 3
  remote-message-service:
    enable: {$proxy}
    identifier: {$proxy-id}
    proxy: {$proxy-exchange-mode}
    host: {$proxy-exchange-host}
    port: {$proxy-exchange-port}
    key: {$proxy-exchange-key}

