config:
  ip-defender:
    service: "baidu" #optional value: baidu|ip-api|pconline|real-ip
    record: true #是否记录IP属地变化
    auto-ban: false #是否自动封禁
    auto-ban-day-time: 0 #封禁的时间，往下为天，时，分，秒
    auto-ban-hour-time: 0
    auto-ban-minute-time: 10
    auto-ban-second-time: 0
  explosion-defender:
    override-explosion: true
    record: true
    broadcast: true
  permission-manager:
    default-group: --player