config:
  advanced-ban-command:
    broadcast: true
  kick-on-reload:
    op-ignore: false
  tps-bar:
    line: "{#white}TPS: {tps}     {#white}MSPT: {mspt}"
  chat-report:
    append: '{click(command,/chat-report %s);color(red)}[!]' #report interactive text
  chat-filter:
    filter-sign: true #determine weather will filter sign edits or not.
    filter-anvil: true #determine weather will filter anvil renames or not.
    except-player: true #player name will be excepted from process.
    cover: true #detected keywords will not be replaced, but still be detected.
    cover-char: '*' #using this char to replace keyword.
    handled-commands: [ "say","tell","mail" ] #commands will be handled as they attempt to send message.
    punish: true #will punish player.
    punish-command: "mute {player} 3600 {#yellow}[starlight]{#red}BadChatBehavior" #punish player using this command. support other plugins.